### ISSUE TITLE
Restrict connections beyond of Telegram subnets

### ISSUE THREAD

**Issue by an5t** [ex3ndr/telegram-proxy#3]
Making public proxy server allowing connections to the whole world does not seems a good idea. I think it would be nice to permit connections to Telegram networks only.

**Comment by ex3ndr** [comment]
We need to have a list of IP addresses of Telegram Servers and keep it in sync. Do you have one?

**Comment by an5t** [comment]
I have permitted the following ones on my proxy earlier, and everything worked well:
```
149.154.160.0/20
91.108.0.0/19
91.108.36.0/22
91.108.56.0/22
2001:67c:4e8::/48
2001:b28:f23c::/48
2001:b28:f23f::/48
2001:b28:f23d::/48
```
BUT now it seems that Telegram started using additional addresses (including Amazon's ones) to breakthrough block. So at present it may be bad idea to restrict connections beyond listed networks.

**Comment by iworker** [comment]
Will it be a good solution to use env variable, for example, IP_ADDRESSES, to configure all these networks, like:
`
docker run --restart always -d --name telegram-proxy -e "IP_ADDRESSES=8.8.8.0/22,8.8.4.4" -p 1080:1080 ex3ndr/telegram-proxy
`
?

**Comment by ulyan** [comment]
Smth like this https://github.com/ulyanchesnokov/tgproxy/blob/master/sockd.conf
